steps:
- name: 'gcr.io/cloud-builders/npm'
  dir: 'backend'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  dir: 'backend'
  args: ['run', 'build']
- name: "gcr.io/cloud-builders/gcloud"
  dir: 'backend'
  args: ["app", "deploy"]
timeout: "1600s"
